server:
    port: 8082
spring:
    application:
             name: movie-info-service
    zipkin: 
           base-url: http://localhost:9411/
    sleuth:
          sampler: 
             probability: 1
          traceId128: true                                        
    rabbitmq:
          host: localhost
          port: 5672
          username: guest
          password: guest
logging:
          level:
             org:springframework:web: DEBUG
          pattern:
                  level: "%d{ABSOLUTE} [%X{X-B3-TraceId}/%X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n"                    
api:
  key: 072d17d5d0c890586aa18d06792e14e8
management:
        endpoints: 
               web: 
                 exposure: 
                         include: "*"  