server:
    port: 8082
spring:
    application:
             name: movie-info-service
    logging:
          level:
             org.springframework.web: DEBUG
             org.springframework.cloud.netflix.zuul: DEBUG
    zipkin: 
           base-url: http://localhost:9411/
    sleuth:
          sampler: 
             probability: 1                               
    rabbitmq:
          host: localhost
          port: 5672
          username: guest
          password: guest          
api:
  key: 072d17d5d0c890586aa18d06792e14e8
management:
        endpoints: 
               web: 
                 exposure: 
                         include: "*"  