server:
    port: 9091
spring:
     application:
              name: auth-server
management:
        endpoints: 
               web: 
                 exposure: 
                         include: "*"              
