server:
    port: 8085
spring:
     sleuth:
          sampler: 
             probability: 1
          traceId128: true
                  
#     rabbitmq:
#          host: localhost
#          port: 5672
#          username: guest 
#          password: guest 
#logging:
#          level:
#             root: INFO
#             org:springframework:web: DEBUG
#          pattern:
#                  level: "%d{ABSOLUTE} [%X{X-B3-TraceId}/%X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n"
management:
        endpoints: 
               web: 
                 exposure: 
                         include: "*"                   
                                                         