server:
    port: 8083
spring:
   application:
            name: ratings-data-service
   logging:
          level:
             org.springframework.web: DEBUG
             org.springframework.cloud.netflix.zuul: DEBUG     
   zipkin: 
         base-url: http://localhost:9411/
   sleuth:
          sampler: 
             probability: 1        
                         
   rabbitmq:
          host: localhost
          port: 5672
          username: guest
          password: guest            
management:
        endpoints: 
               web: 
                 exposure: 
                         include: "*"    
