server:
    port: 8083
spring:
   application:
            name: ratings-data-service
   rabbitmq:
          host: localhost
          port: 5672
          username: guest
          password: guest            
management:
        endpoints: 
               web: 
                 exposure: 
                         include: "*"    
