server:
    port: 8989
spring:
   application:
            name: trurbine-stream-service
   rabbitmq:
          host: localhost
          port: 5672
          username: guest
          password: guest            
eureka:
     client:
         register-with-eureka: false
         fetch-registry: false
management:
        endpoints: 
               web: 
                 exposure: 
                         include: "*"
                           