server:
     port: 8081
spring:
     application:
              name: movie-catalog-service
     rabbitmq:
          host: localhost
          port: 5672
          username: guest
          password: guest         
management:
        endpoints: 
               web: 
                 exposure: 
                         include: "*"