server:
     port: 8081
spring:
     application:
              name: movie-catalog-service
     logging:
          level:
             org.springframework.web: DEBUG
     zipkin: 
           base-url: http://localhost:9411/
     sleuth:
          sampler: 
             probability: 1                 
     rabbitmq:
          host: localhost
          port: 5672
          username: guest
          password: guest         
management:
        endpoints: 
               web: 
                 exposure: 
                         include: "*"
                        