spring:
     application:
              name: api-gateway-service
     logging:
          level:
             org:springframework:web: DEBUG
             org:springframework:cloud:netflix:zuul: DEBUG
     main:
        allow-bean-definition-overriding: true        
        
zuul:
    routes:
       movie-catalog:
                  path: /movie_catalog/**
                  serviceId: movie-catalog-service
       movie-info:
                path: /movie_info/**
                serviceId: movie-info-service
       ratings-data:
                 path: /ratings_data/**
                 serviceId: ratings-data-service      
ribbon:
    eureka:
         enabled: true
server:
    port: 8084
    
  

                                          

